import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navigation from "../components/navigation/navigation";
import Footer from "../components/footer/footer";
import Hero from "../components/hero/hero";
import Quotes from "../components/quotes/quotes";
import PartnerProgram from "../components/partnerProgram/partnerProgram";
import SignIn from "../components/SignIn/signIn";
import { joinClassNames } from "../utilities/componentsHelpers";
import NotificationsDemo from "../components/notificationsDemo";
import applicationsData from "../applicationsData";
import quotesData from "../quotesData";
import Applications from "../components/applications/applications";

export default function Home() {
  const filters = [
    "Aktuelles",
    "Recherche",
    "Planung",
    "Distribution",
    "Audio",
    "Video",
    "Visuals",
    "Daten",
    "Alle anzeigen",
  ];
  return (
    <div>
      <Head>
        <title>dpa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation className={joinClassNames(styles.navigation)} />

      <main>
        <Hero className={styles.hero} />
        <Quotes className={styles.quotes} data={quotesData} />
        <Applications
          className={styles.applications}
          filters={filters}
          applications={applicationsData}
        />
        <NotificationsDemo />
        <PartnerProgram className={styles.partnerProgram} />
        <SignIn className={styles.logIn} />
      </main>

      <Footer className={joinClassNames(styles.footer)} />
    </div>
  );
}
